"""Unit tests for bsl_telemetry.trace_check (Wi-Fi guard [WG1] trace judge).

Covers docs/plans/2026-07-06-wifi-guard-trace-bench.md section 5's PASS/FAIL/
INVALID synthetic-log requirements for R1-R5 + common validity + R4. Hand-
built logs use a small line-builder (`Log`) plus a tick/epoch simulator
(`GuardSim`) that reproduces the emitter's tk-ep/ev-i bookkeeping precisely
enough to exercise the drain-attribution rule (section 5 "イベント起点窓の
drain アンカー") including both interleavings.

Fixture-driven cross-validation (section 4 D11: emitter-generated logs in
tools/telemetry/tests/fixtures/<scenario>__<EXPECTED>__<desc>.log) is
generated by a separate, concurrently-running work item; if the fixtures
directory is empty at test time, TestFixtures.test_fixtures skips itself
(reported explicitly, not silently).
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bsl_telemetry import trace_check as tc

TICK_US = 50_000  # 20 Hz nominal telemetry tick (matches trace_check's default)
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"


def _f(v):
    return "-" if v is None else str(v)


class Log:
    """Minimal [WG1] line builder. `s` is assigned in call order (matching
    physical file order), `t` is whatever the caller has advanced to.
    """

    def __init__(self):
        self.lines = []
        self._s = 0
        self.t = 0

    def _emit(self, body: str) -> None:
        self.lines.append(f"[WG1] s={self._s} t={self.t} {body}")
        self._s += 1

    def raw(self, line: str) -> None:
        """Escape hatch for deliberately malformed/corrupted lines."""
        self.lines.append(line)
        self._s += 1

    def boot(self, v=1, fw="abc1234", dev="core2-a4cf"):
        self._emit(f"boot v={v} fw={fw} dev={dev}")

    def tk(self, fsm, arm, ep):
        self._emit(f"tk fsm={_f(fsm)} arm={_f(arm)} ep={ep}")

    def ev(self, kind, r=None, i=None):
        self._emit(f"ev={kind} r={_f(r)} i={_f(i)}")

    def op(self, kind, fsm, arm, q, udpr, res=0, dur=1000, fsm2=None, arm2=None, fsm3=None, arm3=None):
        body = f"op={kind} fsm={_f(fsm)} arm={_f(arm)} q={q} udpr={udpr} res={_f(res)} dur={dur}"
        if kind == "bp":
            body += f" fsm2={_f(fsm2)} arm2={_f(arm2)} fsm3={_f(fsm3)} arm3={_f(arm3)}"
        self._emit(body)

    def st(self, fsm, arm, q, conn, cing, udpr, librp, ab, roff, latch, pwf=0, sf=0, evo=0):
        self._emit(
            f"st fsm={_f(fsm)} arm={_f(arm)} q={q} conn={conn} cing={cing} udpr={udpr} "
            f"librp={librp} ab={ab} roff={roff} latch={latch} pwf={pwf} sf={sf} evo={evo}"
        )

    def hb(self, fsm, arm, q, conn, cing, udpr, librp, ab, roff, latch, pwf=0, sf=0, evo=0,
           heap=100000, heapmin=90000, evdrop=0, flmax=1000, stkmin=4000, tick=0):
        self._emit(
            f"hb fsm={_f(fsm)} arm={_f(arm)} q={q} conn={conn} cing={cing} udpr={udpr} "
            f"librp={librp} ab={ab} roff={roff} latch={latch} pwf={pwf} sf={sf} evo={evo} "
            f"heap={heap} heapmin={heapmin} evdrop={evdrop} flmax={flmax} stkmin={stkmin} tick={tick}"
        )

    def drop(self, n):
        self._emit(f"drop n={n}")

    def advance(self, us):
        self.t += us

    def text(self):
        return "\n".join(self.lines) + "\n"


class GuardSim:
    """Reproduces the emitter's tk.ep (pre-drain cumulative drained count)
    and ev.i (guard-tracked arrival counter) bookkeeping precisely, so hand-
    built logs can exercise trace_check's epoch-based drain attribution
    (section 5) under either interleaving:

      - `event()` then `tick()` (or `tick_start()`+`drain_pending()` in the
        same call): the event drains in the tick whose `tick_start()` prints
        the *old* (pre-event) `ep` and whose `drain_pending()` call is the
        first to include it -- i.e. the current tick.
      - `tick()` (draining nothing new) then `event()` then the *next*
        `tick()`: the event is only visible to guard from the next tick's
        drain onward -- i.e. it is pre-drain for the current tick.
    """

    def __init__(self, log: Log, tick_us: int = TICK_US):
        self.log = log
        self.tick_us = tick_us
        self.drained = 0
        self.arrived = 0
        self.pending = []
        self.tick_count = 0

    def event(self, kind: str, r=None) -> int:
        self.arrived += 1
        self.log.ev(kind, r=r, i=self.arrived)
        self.pending.append(kind)
        return self.arrived

    def library_event(self, kind: str, r=None) -> None:
        self.log.ev(kind, r=r, i=None)

    def tick_start(self, fsm, arm) -> int:
        self.log.advance(self.tick_us)
        self.log.tk(fsm=fsm, arm=arm, ep=self.drained)
        idx = self.tick_count
        self.tick_count += 1
        return idx

    def drain_pending(self) -> None:
        self.drained += len(self.pending)
        self.pending = []

    def tick(self, fsm, arm) -> int:
        idx = self.tick_start(fsm, arm)
        self.drain_pending()
        return idx


CLEAN_TAIL_CTX = dict(conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)


def finish(log: Log, sim: GuardSim, fsm, arm, q, **overrides) -> None:
    """Append >= 2 clean hb rows well after the last activity, satisfying
    the common-validity tail requirements (hb>=2, last line hb, hb after
    last ev/op; section 5 "ログ末尾・カバレッジの完全性").
    """
    ctx = dict(CLEAN_TAIL_CTX)
    ctx.update(overrides)
    for k in range(2):
        log.advance(1_000_000)
        sim.tick(fsm=fsm, arm=arm)
        log.hb(fsm=fsm, arm=arm, q=q, tick=sim.tick_count, **ctx)


def get_outcome(result: tc.CheckResult, name: str) -> tc.Outcome:
    return next(o for o in result.outcomes if o.name == name)


# ---------------------------------------------------------------------------
# Grammar / preprocessing (section 5 "前処理")
# ---------------------------------------------------------------------------


class TestGrammarAndPreprocessing(unittest.TestCase):
    def _base(self) -> Log:
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=0, arm=0)
        log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=0, arm=0, q=0, conn=0, udpr=0)
        return log

    def test_boot_missing_is_invalid(self):
        log = Log()
        sim = GuardSim(log)
        sim.tick(fsm=0, arm=0)
        log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=0, arm=0, q=0, conn=0, udpr=0)
        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")

    def test_multiple_boot_lines_is_invalid(self):
        log = self._base()
        log.boot()
        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")
        self.assertIn("multiple boot", result.outcomes[0].evidence[0])

    def test_line_before_boot_is_invalid(self):
        log = Log()
        log.tk(fsm=0, arm=0, ep=0)
        log.boot()
        text = log.text()
        result = tc.check_log(text, "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")

    def test_s_gap_is_invalid(self):
        log = self._base()
        text = log.text()
        lines = text.splitlines()
        # Bump every s value from the 3rd line onward by 1 to create a gap.
        patched = lines[:2]
        for line in lines[2:]:
            tokens = line.split()
            s_val = int(tokens[1][2:])
            tokens[1] = f"s={s_val + 1}"
            patched.append(" ".join(tokens))
        result = tc.check_log("\n".join(patched) + "\n", "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")
        self.assertIn("gap in s sequence", result.outcomes[0].evidence[0])

    def test_duplicate_s_is_invalid(self):
        log = self._base()
        text = log.text()
        lines = text.splitlines()
        # Force the second line's s to collide with the first.
        tokens = lines[1].split()
        tokens[1] = "s=0"
        lines[1] = " ".join(tokens)
        result = tc.check_log("\n".join(lines) + "\n", "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")

    def test_malformed_wg1_line_is_invalid(self):
        log = self._base()
        log.raw("[WG1] s=999 t=999999 bogus_record_type foo=bar")
        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")

    def test_non_wg1_lines_are_ignored(self):
        log = self._base()
        text = "garbled baud-switch noise \xff\xfe\n" + log.text()
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "preprocessing").status, "PASS")
        self.assertEqual(get_outcome(result, "common").status, "PASS")

    def test_missing_required_field_is_invalid(self):
        log = Log()
        log.boot()
        # Hand-craft a tk line missing `ep`.
        log.raw(f"[WG1] s=1 t=50000 tk fsm=0 arm=0")
        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(result.outcomes[0].status, "INVALID")


# ---------------------------------------------------------------------------
# Common validity (section 5 "共通妥当性")
# ---------------------------------------------------------------------------


class TestCommonValidity(unittest.TestCase):
    def _clean_t1_log(self) -> Log:
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)
        return log

    def test_clean_log_common_validity_pass(self):
        log = self._clean_t1_log()
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "PASS")

    def test_drop_line_is_invalid(self):
        log = self._clean_t1_log()
        log.drop(3)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")
        self.assertFalse(result.ok)

    def test_hb_evdrop_nonzero_is_invalid(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX, evdrop=2)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_hb_evo_nonzero_is_invalid(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0, evo=1)
        finish(log, sim, fsm=1, arm=0, q=0, evo=1)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_hb_flmax_over_budget_is_invalid(self):
        log = self._clean_t1_log()
        text = log.text().replace("flmax=1000", "flmax=40001")
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_hb_flmax_at_budget_passes(self):
        log = self._clean_t1_log()
        text = log.text().replace("flmax=1000", "flmax=40000")
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "common").status, "PASS")

    def test_stkmin_missing_is_invalid(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.raw(
            f"[WG1] s={log._s} t={log.t} hb fsm=1 arm=0 q=0 conn=1 cing=0 udpr=1 librp=0 ab=0 roff=0 "
            f"latch=0 pwf=0 sf=0 evo=0 heap=100000 heapmin=90000 evdrop=0 flmax=1000 tick=1"
        )
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX, tick=2)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(result.outcomes[0].status, "INVALID")  # missing field -> malformed -> preprocessing

    def test_stkmin_512_is_invalid(self):
        log = self._clean_t1_log()
        text = log.text().replace("stkmin=4000", "stkmin=512")
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_stkmin_2048_passes(self):
        log = self._clean_t1_log()
        text = log.text().replace("stkmin=4000", "stkmin=2048")
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "common").status, "PASS")

    def test_only_one_hb_is_invalid(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX, tick=1)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_last_line_not_hb_is_invalid(self):
        log = self._clean_t1_log()
        log.advance(1_000_000)
        sim = GuardSim(log)
        sim.tick_count = 3
        log.tk(fsm=1, arm=0, ep=0)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_no_hb_after_last_ev_op_is_invalid(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX, tick=1)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.op("bp", fsm=1, arm=0, q=0, udpr=1, dur=100)
        log.advance(1_000_000)
        sim.tick(fsm=1, arm=0)
        log.hb(fsm=1, arm=0, q=0, **CLEAN_TAIL_CTX, tick=2)
        # Rewrite text with an ev/op appended after the last hb by hand.
        text = log.text() + f"[WG1] s={log._s} t={log.t + 1} ev=scan r=- i=-\n"
        result = tc.check_log(text, "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")

    def test_latch_set_from_log_start_is_invalid_not_fail(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=1)
        finish(log, sim, fsm=1, arm=0, q=0, latch=1)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "common").status, "INVALID")


# ---------------------------------------------------------------------------
# R1 (T1, C1)
# ---------------------------------------------------------------------------


class TestR1(unittest.TestCase):
    def test_pass_quiet_balancing_window(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=0, arm=0)
        log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)  # genuine first setup bp
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        for _ in range(5):
            sim.tick(fsm=2, arm=0)
            log.op("bp", fsm=2, arm=0, q=1, udpr=1, dur=200, fsm2=2, arm2=0, fsm3=2, arm3=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R1").status, "PASS")

    def test_fail_library_activity_in_transition_tick(self):
        """遷移 tick 内（tk fsm=2 の後・st fsm=2 の前）に ev=scan が記録された
        場合 -> R1 FAIL（窓を post-tick st で開くと見逃す偽 PASS の回帰防止）."""
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick_start(fsm=2, arm=0)  # tk fsm=2 printed -- guard already treats this tick as Balancing
        sim.library_event("scan")  # recorded before the post-tick st -- must still be caught
        sim.drain_pending()
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R1")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("ev=scan", outcome.evidence[0])

    def test_pass_no_activity_in_transition_tick_regression(self):
        """同位置（tk fsm=2 の後・st fsm=2 の前）に op も ev もない場合 ->
        PASS（回帰: tk アンカー化そのものが偽 FAIL を作らないことの確認）."""
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick_start(fsm=2, arm=0)
        sim.drain_pending()
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R1").status, "PASS")

    def test_fail_forbidden_op_inside_window(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.op("begin", fsm=2, arm=0, q=1, udpr=0, dur=500)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R1").status, "FAIL")

    def test_fail_no_op_but_library_activity_inside_window(self):
        """opなし+ライブラリ活動: op 行の不在だけでは禁止負荷を証明しない."""
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        sim.library_event("scan")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R1")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("ev=scan", outcome.evidence[0])

    def test_fail_dirty_entry_window_not_eligible(self):
        """No window ever starts with cing=0∧librp=0∧ab=0 -> scenario not exercised."""
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=0, cing=1, udpr=0, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=0, cing=1, udpr=0, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R1").status, "FAIL")

    def test_fail_bp_udpr0_inside_window(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.op("bp", fsm=2, arm=0, q=1, udpr=0, dur=200, fsm2=2, arm2=0, fsm3=2, arm3=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t1")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R1").status, "FAIL")


# ---------------------------------------------------------------------------
# R2 (T2, C2)
# ---------------------------------------------------------------------------


def _r2_prefix() -> tuple[Log, GuardSim]:
    log = Log()
    log.boot()
    sim = GuardSim(log)
    sim.tick(fsm=0, arm=0)
    log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
    sim.tick(fsm=1, arm=0)
    log.st(fsm=1, arm=0, q=0, conn=0, cing=1, udpr=0, librp=0, ab=0, roff=0, latch=0)  # CONNECTING
    return log, sim


class TestR2(unittest.TestCase):
    def test_pass_immediate_abort_same_tick(self):
        """遷移 tick 内で即時発行される abort (op.t が最初の q=1 st より前) -> PASS."""
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)  # Balancing entered mid-CONNECTING
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)  # immediate abort, same tick
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)  # drains confirmation
        log.st(fsm=2, arm=0, q=1, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R2").status, "PASS")

    def test_fail_no_scenario_exercised(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)
        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R2").status, "FAIL")

    def test_fail_bp_intrudes_window(self):
        """禁止窓内の bp 混入 -> FAIL."""
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
        sim.tick(fsm=2, arm=0)
        log.op("bp", fsm=2, arm=0, q=1, udpr=0, dur=200, fsm2=2, arm2=0, fsm3=2, arm3=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R2").status, "FAIL")

    def test_fail_radio_off_intrudes_window(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
        sim.tick(fsm=2, arm=0)
        log.op("radio_off", fsm=2, arm=0, q=1, udpr=0, dur=200)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0, latch=1)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R2").status, "FAIL")

    def test_fail_slow_disconnect_over_dur_budget(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=150_000)  # > 100ms budget
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R2")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("dur=", outcome.evidence[0])

    def test_pass_bounded_retry_with_q1(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)  # first disc fails
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)  # retry, still q=1
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R2").status, "PASS")

    def test_fail_retry_with_q0(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=0, udpr=0, dur=3000)  # retry issued after quiet released -> FAIL
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R2").status, "FAIL")

    def test_fail_retry_exhausted_radio_off(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        for _ in range(5):  # first + 4 retries, all q=1
            log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
            sim.tick(fsm=2, arm=0)
        log.op("radio_off", fsm=2, arm=0, q=1, udpr=0, dur=100)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0, latch=1)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R2")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("radio_off", outcome.evidence[0])

    def test_fail_retry_count_exceeds_bound(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        for _ in range(6):  # first + 5 retries > bound of 4
            log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
            sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R2")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("exceeds bound", outcome.evidence[0])

    def test_fail_no_completion_event(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R2")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("no post-abort completion event", outcome.evidence[0])

    def test_fail_additional_activity_after_completion(self):
        log, sim = _r2_prefix()
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=0, dur=3000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)  # drains confirmation
        sim.library_event("scan")  # extra library activity after confirmed completion
        sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1, conn=0, udpr=0)

        result = tc.check_log(log.text(), "t2")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R2")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("after abort completion confirmation", outcome.evidence[0])


# ---------------------------------------------------------------------------
# R3 (T3, C3 前半)
# ---------------------------------------------------------------------------


def _r3_prefix() -> tuple[Log, GuardSim]:
    log = Log()
    log.boot()
    sim = GuardSim(log)
    sim.tick(fsm=0, arm=0)
    log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
    log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)  # genuine first setup bp
    sim.tick(fsm=1, arm=0)
    log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)  # connected, idle
    sim.tick(fsm=2, arm=0)
    log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)  # Balancing
    return log, sim


class TestR3(unittest.TestCase):
    def test_pass_clean_episode(self):
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # drain tick: abort issued this tick
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=5000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)  # drains confirmation (later tick, satisfies "post-abort")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3").status, "PASS")

    def test_pass_same_tick_disc_and_gotip_clean_cancel(self):
        """同一 tick 内の disc(r!=8) + gotip(in-flight residue, librp が st に
        一度も現れない正しいキャンセル) -> PASS."""
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.event("gotip")  # in-flight residue, permitted before completion confirmation
        sim.tick(fsm=2, arm=0)  # both drain this tick
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=4000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3").status, "PASS")

    def test_pass_no_ab1_observed_in_st(self):
        """abort 開始と完了が近接し st では ab=1 を観測しない系列 -> PASS."""
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=1000)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)  # confirmation drains next tick; no st shows ab=1 anywhere
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3").status, "PASS")

    def test_fail_slow_disconnect(self):
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=200_000)  # over budget
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3").status, "FAIL")

    def test_fail_bp_intrudes_forbidden_window_interleaving_1(self):
        """両インターリーブ (1): tk 記録後・guard drain 前にイベント到着
        (同 tick 内で drain) -> その tick の bp は禁止窓内 -> FAIL."""
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # same-tick drain (interleaving 1)
        log.op("bp", fsm=2, arm=0, q=1, udpr=1, dur=200, fsm2=2, arm2=0, fsm3=2, arm3=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=3000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3").status, "FAIL")

    def test_pass_bp_before_drain_tick_interleaving_2(self):
        """両インターリーブ (2): guard drain 後・trySend 前にイベント到着
        (次 tick 帰属) -> 現 tick の bp は pre-drain -> PASS."""
        log, sim = _r3_prefix()
        sim.tick(fsm=2, arm=0)  # tick T: nothing pending yet, drains nothing
        log.op("bp", fsm=2, arm=0, q=1, udpr=1, dur=200, fsm2=2, arm2=0, fsm3=2, arm3=0)  # pre-drain bp
        sim.event("disc", r=5)  # arrives after tick T's own drain step already ran
        sim.tick(fsm=2, arm=0)  # tick T+1: drains it now -> anchor = T+1, T's bp excluded
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=3000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3").status, "PASS")

    def test_invalid_drain_attribution_impossible_at_tail(self):
        """末尾帰属不能 (i を消費する次 tick が存在しない) -> INVALID."""
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        # No further tick ever drains it (log ends).
        log.raw(f"[WG1] s={log._s} t={log.t + 1_000_000} hb fsm=2 arm=0 q=1 conn=1 cing=0 udpr=1 "
                f"librp=0 ab=0 roff=0 latch=0 pwf=0 sf=0 evo=0 heap=100000 heapmin=90000 evdrop=0 "
                f"flmax=1000 stkmin=4000 tick=1")
        log.advance(1_000_000)
        log.hb(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0, tick=2)

        result = tc.check_log(log.text(), "t3")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3").status, "INVALID")

    def test_fail_additional_disc_after_completion(self):
        """abort 完了確認後の追加 disc/scan -> FAIL."""
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=3000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)  # confirmed
        sim.event("disc", r=3)  # extra disc after confirmation -> FAIL
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3").status, "FAIL")


# ---------------------------------------------------------------------------
# R3b (T3b, C3 後半)
# ---------------------------------------------------------------------------


class TestR3b(unittest.TestCase):
    def _completed_first_episode(self):
        log, sim = _r3_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)
        log.op("disc", fsm=2, arm=0, q=1, udpr=1, dur=3000)
        sim.tick(fsm=2, arm=0)
        sim.event("disc", r=8)
        sim.tick(fsm=2, arm=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        return log, sim

    def test_pass_full_scenario(self):
        log, sim = self._completed_first_episode()
        # (ii) reconnection
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)  # drains gotip; context q=0 at this position
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        # Balancing again, then burnt-AP re-loss.
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit drain tick
        # Hold fsm=2 for >= 20s with zero op/ev activity.
        for _ in range(410):  # 410 * 50ms ~= 20.5s
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3b").status, "PASS")

    def test_pass_grace_window_duplicate_disc_nonself_reason(self):
        """(a) hit+1 tick 以内の disc r=200（非自発的切断の重複配送）-> PASS（猶予）."""
        log, sim = self._completed_first_episode()
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit drain tick T
        sim.event("disc", r=200)  # duplicate non-self-initiated delivery of the same AP loss
        sim.tick(fsm=2, arm=0)  # drains at T+1 -- inside the 2-tick grace
        for _ in range(408):
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R3b").status, "PASS")

    def test_fail_grace_window_disc_r8_is_never_tolerated(self):
        """(b) hit+1 tick の disc r=8 -> FAIL（再アーム疑い、猶予窓内でも不可）."""
        log, sim = self._completed_first_episode()
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit drain tick T
        sim.event("disc", r=8)  # self-initiated ASSOC_LEAVE -- one-shot re-arm signature
        sim.tick(fsm=2, arm=0)  # drains at T+1 -- inside grace, but r=8 is never tolerated
        for _ in range(408):
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R3b")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("r=8", outcome.evidence[0])

    def test_fail_disc_nonself_after_grace_window(self):
        """(c) 猶予窓後の disc r!=8 -> FAIL（既存確認: 猶予は 2 tick に限られる）."""
        log, sim = self._completed_first_episode()
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit drain tick T
        for _ in range(5):  # well beyond the 2-tick grace window
            sim.tick(fsm=2, arm=0)
        sim.event("disc", r=200)  # additional non-self disc, past the settling grace period
        sim.tick(fsm=2, arm=0)
        for _ in range(400):
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R3b")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("settling window", outcome.evidence[0])

    def test_invalid_observation_window_too_short(self):
        log, sim = self._completed_first_episode()
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit
        for _ in range(20):  # only ~1s -- far short of the 20s minimum
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3b").status, "INVALID")

    def test_fail_delayed_activity_at_18s(self):
        """hit の 18 秒後に活動イベントが届く遅延失敗系列 -> FAIL."""
        log, sim = self._completed_first_episode()
        sim.tick(fsm=1, arm=0)
        sim.event("gotip")
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.event("disc", r=5)
        sim.tick(fsm=2, arm=0)  # hit
        for _ in range(360):  # 18s
            sim.tick(fsm=2, arm=0)
        sim.library_event("conn")  # delayed internal reconnect activity at ~18s
        for _ in range(60):  # push total span past 20s
            sim.tick(fsm=2, arm=0)
        finish(log, sim, fsm=2, arm=0, q=1)

        result = tc.check_log(log.text(), "t3b")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R3b").status, "FAIL")

    def test_fail_no_initial_episode(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t3b")
        self.assertFalse(result.ok)
        outcome = get_outcome(result, "R3b")
        self.assertEqual(outcome.status, "FAIL")
        self.assertIn("(i)", outcome.evidence[0])


# ---------------------------------------------------------------------------
# R5 (T5, C5)
# ---------------------------------------------------------------------------


def _r5_prefix() -> tuple[Log, GuardSim]:
    log = Log()
    log.boot()
    sim = GuardSim(log)
    sim.tick(fsm=0, arm=0)
    log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
    sim.tick(fsm=1, arm=0)
    log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)  # connected, idle
    sim.tick(fsm=1, arm=1)
    log.st(fsm=1, arm=1, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)  # arm_pending
    return log, sim


class TestR5(unittest.TestCase):
    def test_pass_clean_episode(self):
        log, sim = _r5_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=1, arm=1)
        log.op("disc", fsm=1, arm=1, q=1, udpr=1, dur=4000)
        sim.tick(fsm=1, arm=1)
        sim.event("disc", r=8)
        sim.tick(fsm=1, arm=1)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t5")
        self.assertTrue(result.ok, result.render())
        self.assertEqual(get_outcome(result, "R5").status, "PASS")

    def test_fail_slow_disconnect(self):
        log, sim = _r5_prefix()
        sim.event("disc", r=5)
        sim.tick(fsm=1, arm=1)
        log.op("disc", fsm=1, arm=1, q=1, udpr=1, dur=250_000)
        sim.tick(fsm=1, arm=1)
        sim.event("disc", r=8)
        sim.tick(fsm=1, arm=1)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        result = tc.check_log(log.text(), "t5")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R5").status, "FAIL")

    def test_fail_no_scenario_exercised(self):
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)
        result = tc.check_log(log.text(), "t5")
        self.assertFalse(result.ok)
        self.assertEqual(get_outcome(result, "R5").status, "FAIL")


# ---------------------------------------------------------------------------
# R4 (all logs, C4)
# ---------------------------------------------------------------------------


class TestR4(unittest.TestCase):
    def _tail_only_log(self, extra_lines_fn) -> Log:
        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=0, arm=0)
        log.st(fsm=0, arm=0, q=0, conn=0, cing=0, udpr=0, librp=0, ab=0, roff=0, latch=0)
        extra_lines_fn(log, sim)
        finish(log, sim, fsm=1, arm=0, q=0)
        return log

    def test_pass_setup_bp_gated_on_q0(self):
        def build(log, sim):
            sim.tick(fsm=0, arm=0)
            log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)  # first bp overall
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "R4").status, "PASS")

    def test_pass_reused_bp_outside_balancing_no_warn(self):
        """A reused (udpr=1) send outside any real-time Balancing/arm window
        overlaps nothing -> clean PASS, no WARN note."""
        def build(log, sim):
            sim.tick(fsm=0, arm=0)
            log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)  # setup
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
            log.op("bp", fsm=1, arm=0, q=0, udpr=1, dur=100, fsm2=1, arm2=0, fsm3=1, arm3=0)  # reused, idle-mode send

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        outcome = get_outcome(result, "R4")
        self.assertEqual(outcome.status, "PASS")
        self.assertTrue(all("WARN" not in e for e in outcome.evidence))

    def test_fail_setup_class_bp_with_q1(self):
        """stale snapshot 中の prewarm 試行 (q=1∧fsm=1∧arm=0 の bp) -> R4 FAIL."""
        def build(log, sim):
            sim.tick(fsm=1, arm=0)
            # udpr=0 (setup-class) issued while q=1, even though sampled fsm/arm look idle.
            log.op("bp", fsm=1, arm=0, q=1, udpr=0, dur=800, fsm2=1, arm2=0, fsm3=1, arm3=0)
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "R4").status, "FAIL")

    def test_fail_first_bp_in_log_not_q0(self):
        def build(log, sim):
            sim.tick(fsm=2, arm=0)
            log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
            log.op("bp", fsm=2, arm=0, q=1, udpr=1, dur=100, fsm2=2, arm2=0, fsm3=2, arm3=0)  # first bp, q=1
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "R4").status, "FAIL")

    def test_fail_bp_during_balancing_with_udpr0(self):
        def build(log, sim):
            sim.tick(fsm=0, arm=0)
            log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)
            sim.tick(fsm=2, arm=0)
            log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
            log.op("bp", fsm=2, arm=0, q=1, udpr=0, dur=800, fsm2=2, arm2=0, fsm3=2, arm3=0)  # setup during Balancing
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "R4").status, "FAIL")

    def test_fail_setup_bp_overlaps_realtime_window(self):
        def build(log, sim):
            sim.tick(fsm=0, arm=0)
            # Setup-class bp whose pre/post re-sample shows an overlap with a real-time Balancing window.
            log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=2, arm2=0, fsm3=0, arm3=0)
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        self.assertEqual(get_outcome(result, "R4").status, "FAIL")

    def test_warn_reused_bp_overlaps_realtime_window(self):
        def build(log, sim):
            sim.tick(fsm=0, arm=0)
            log.op("bp", fsm=0, arm=0, q=0, udpr=0, dur=800, fsm2=0, arm2=0, fsm3=0, arm3=0)
            sim.tick(fsm=2, arm=0)
            log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
            # Reused (udpr=1) send whose immediate re-sample shows fsm2/fsm3=2 (expected -- it's mid-Balancing).
            log.op("bp", fsm=2, arm=0, q=1, udpr=1, dur=100, fsm2=2, arm2=0, fsm3=2, arm3=0)
            sim.tick(fsm=1, arm=0)
            log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)

        log = self._tail_only_log(build)
        result = tc.check_log(log.text(), "t1")
        outcome = get_outcome(result, "R4")
        self.assertEqual(outcome.status, "WARN")
        self.assertTrue(result.ok)  # WARN does not block exit code


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


class TestCLI(unittest.TestCase):
    def test_main_returns_zero_on_pass(self, tmp_path=None):
        import tempfile

        log = Log()
        log.boot()
        sim = GuardSim(log)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=2, arm=0)
        log.st(fsm=2, arm=0, q=1, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        sim.tick(fsm=1, arm=0)
        log.st(fsm=1, arm=0, q=0, conn=1, cing=0, udpr=1, librp=0, ab=0, roff=0, latch=0)
        finish(log, sim, fsm=1, arm=0, q=0)

        with tempfile.NamedTemporaryFile("w", suffix=".log", delete=False) as fh:
            fh.write(log.text())
            path = fh.name
        try:
            rc = tc.main(["--scenario", "t1", path])
        finally:
            Path(path).unlink(missing_ok=True)
        self.assertEqual(rc, 0)

    def test_main_returns_nonzero_on_invalid(self):
        import tempfile

        with tempfile.NamedTemporaryFile("w", suffix=".log", delete=False) as fh:
            fh.write("not a wg1 log at all\n")
            path = fh.name
        try:
            rc = tc.main(["--scenario", "t1", path])
        finally:
            Path(path).unlink(missing_ok=True)
        self.assertEqual(rc, 1)


# ---------------------------------------------------------------------------
# Fixture cross-validation (section 4 D11) -- generated by a concurrent work
# item; skip cleanly (with an explicit message) if none exist yet.
# ---------------------------------------------------------------------------


class TestFixtures(unittest.TestCase):
    def test_fixtures(self):
        if not FIXTURES_DIR.is_dir():
            self.skipTest(f"fixtures directory not present yet: {FIXTURES_DIR}")
        fixture_paths = sorted(FIXTURES_DIR.glob("*.log"))
        if not fixture_paths:
            self.skipTest(f"no fixture logs found under {FIXTURES_DIR} yet")

        valid_scenarios = set(tc.RULE_BY_SCENARIO) | {"common"}
        valid_expected = {"PASS", "FAIL", "INVALID"}
        failures = []
        for path in fixture_paths:
            parts = path.stem.split("__")
            if len(parts) < 2:
                failures.append(f"{path.name}: filename does not match <scenario>__<EXPECTED>__<desc>.log")
                continue
            scenario, expected = parts[0], parts[1]
            if scenario not in valid_scenarios or expected not in valid_expected:
                failures.append(f"{path.name}: unrecognized scenario/expected in filename")
                continue
            check_scenario = scenario if scenario != "common" else "t1"
            text = path.read_text(encoding="utf-8", errors="replace")
            result = tc.check_log(text, check_scenario)
            if scenario == "common":
                actual = get_outcome(result, "common").status
            else:
                actual = get_outcome(result, tc.RULE_BY_SCENARIO[scenario]).status
            if expected == "PASS":
                ok = actual in ("PASS", "WARN")
            else:
                ok = actual == expected
            if not ok:
                failures.append(f"{path.name}: expected {expected}, got {actual} ({result.render()})")

        if failures:
            self.fail("\n".join(failures))


if __name__ == "__main__":
    unittest.main()
